#!/bin/bash

python pq_preagg.py tile_4443_clipped.parquet
python pq_preagg.py tile_4444_clipped.parquet
python pq_preagg.py tile_5122_clipped.parquet
python pq_preagg.py tile_5221_clipped.parquet
python pq_preagg.py tile_5312_clipped.parquet
python pq_preagg.py tile_5322_clipped.parquet
python pq_preagg.py tile_5411_clipped.parquet
python pq_preagg.py tile_5412_clipped.parquet
python pq_preagg.py tile_5421_clipped.parquet
python pq_preagg.py tile_5422_clipped.parquet
python pq_preagg.py tile_5511_clipped.parquet
python pq_preagg.py tile_5124_clipped.parquet
python pq_preagg.py tile_5213_clipped.parquet
python pq_preagg.py tile_5313_clipped.parquet
python pq_preagg.py tile_5314_clipped.parquet
python pq_preagg.py tile_5323_clipped.parquet
python pq_preagg.py tile_5324_clipped.parquet
python pq_preagg.py tile_5413_clipped.parquet
python pq_preagg.py tile_5414_clipped.parquet
python pq_preagg.py tile_5423_clipped.parquet
python pq_preagg.py tile_5424_clipped.parquet
python pq_preagg.py tile_5513_clipped.parquet
python pq_preagg.py tile_5141_clipped.parquet
python pq_preagg.py tile_5142_clipped.parquet
python pq_preagg.py tile_5231_clipped.parquet
python pq_preagg.py tile_5232_clipped.parquet
python pq_preagg.py tile_5242_clipped.parquet
python pq_preagg.py tile_5331_clipped.parquet
python pq_preagg.py tile_5332_clipped.parquet
python pq_preagg.py tile_5341_clipped.parquet
python pq_preagg.py tile_5342_clipped.parquet
python pq_preagg.py tile_5431_clipped.parquet
python pq_preagg.py tile_5432_clipped.parquet
python pq_preagg.py tile_5441_clipped.parquet
python pq_preagg.py tile_5442_clipped.parquet
python pq_preagg.py tile_5531_clipped.parquet
python pq_preagg.py tile_5144_clipped.parquet
python pq_preagg.py tile_5233_clipped.parquet
python pq_preagg.py tile_5234_clipped.parquet
python pq_preagg.py tile_5243_clipped.parquet
python pq_preagg.py tile_5244_clipped.parquet
python pq_preagg.py tile_5333_clipped.parquet
python pq_preagg.py tile_5334_clipped.parquet
python pq_preagg.py tile_5343_clipped.parquet
python pq_preagg.py tile_5344_clipped.parquet
python pq_preagg.py tile_5433_clipped.parquet
python pq_preagg.py tile_5434_clipped.parquet
python pq_preagg.py tile_5443_clipped.parquet
python pq_preagg.py tile_5444_clipped.parquet
python pq_preagg.py tile_5533_clipped.parquet
python pq_preagg.py tile_6211_clipped.parquet
python pq_preagg.py tile_6212_clipped.parquet
python pq_preagg.py tile_6221_clipped.parquet
python pq_preagg.py tile_6222_clipped.parquet
python pq_preagg.py tile_6311_clipped.parquet
python pq_preagg.py tile_6312_clipped.parquet
python pq_preagg.py tile_6321_clipped.parquet
python pq_preagg.py tile_6322_clipped.parquet
python pq_preagg.py tile_6411_clipped.parquet
python pq_preagg.py tile_6412_clipped.parquet
python pq_preagg.py tile_6421_clipped.parquet
python pq_preagg.py tile_6422_clipped.parquet
python pq_preagg.py tile_6124_clipped.parquet
python pq_preagg.py tile_6213_clipped.parquet
python pq_preagg.py tile_6214_clipped.parquet
python pq_preagg.py tile_6223_clipped.parquet
python pq_preagg.py tile_6224_clipped.parquet
python pq_preagg.py tile_6313_clipped.parquet
python pq_preagg.py tile_6314_clipped.parquet
python pq_preagg.py tile_6323_clipped.parquet
python pq_preagg.py tile_6324_clipped.parquet
python pq_preagg.py tile_6413_clipped.parquet
python pq_preagg.py tile_6414_clipped.parquet
python pq_preagg.py tile_6423_clipped.parquet
python pq_preagg.py tile_6424_clipped.parquet
python pq_preagg.py tile_6513_clipped.parquet
python pq_preagg.py tile_6241_clipped.parquet
python pq_preagg.py tile_6242_clipped.parquet
python pq_preagg.py tile_6331_clipped.parquet
python pq_preagg.py tile_6332_clipped.parquet
python pq_preagg.py tile_6341_clipped.parquet
python pq_preagg.py tile_6342_clipped.parquet
python pq_preagg.py tile_6431_clipped.parquet
python pq_preagg.py tile_6432_clipped.parquet
python pq_preagg.py tile_6441_clipped.parquet
python pq_preagg.py tile_6442_clipped.parquet
python pq_preagg.py tile_6531_clipped.parquet
python pq_preagg.py tile_6244_clipped.parquet
python pq_preagg.py tile_6333_clipped.parquet
python pq_preagg.py tile_6334_clipped.parquet
python pq_preagg.py tile_6343_clipped.parquet
python pq_preagg.py tile_6344_clipped.parquet
python pq_preagg.py tile_6433_clipped.parquet
python pq_preagg.py tile_6434_clipped.parquet
python pq_preagg.py tile_6443_clipped.parquet
python pq_preagg.py tile_6444_clipped.parquet
python pq_preagg.py tile_6533_clipped.parquet
python pq_preagg.py tile_6534_clipped.parquet
python pq_preagg.py tile_7312_clipped.parquet
python pq_preagg.py tile_7321_clipped.parquet
python pq_preagg.py tile_7322_clipped.parquet
python pq_preagg.py tile_7411_clipped.parquet
python pq_preagg.py tile_7412_clipped.parquet
python pq_preagg.py tile_7414_clipped.parquet
